### ISSUE TITLE
Create a way to build a help

### ISSUE THREAD

**Issue by JulioGold** [jpdillingham/Utility.CommandLine.Arguments#22]
There is a way to create a help automatically?

Thank's

**Comment by jpdillingham** [comment]
Not presently but I'm interested in adding that functionality.

This would involve extending the ```ArgumentAttribute``` class to accept a description and adding a new ```HelpAttribute``` to designate an argument to trigger the help to display when used.  Ideally this would work in conjunction with DataAnnotations, allowing arguments to be marked ```Required``` and ```Optional```.

**Comment by jpdillingham** [comment]
@nickolasacosta looping you in per our conversation
