### ISSUE TITLE
Values can't start with a slash

### ISSUE THREAD

**Issue by MatthiasJentsch** [jpdillingham/Utility.CommandLine.Arguments#26]
If you have a command line like this `--file=/mnt/data/test.xml` the file argument will be empty. The `ArgumentRegEx` finds only the key but not the value. You can find an example here: https://regex101.com/r/SGsVEg/2

**Comment by jpdillingham** [comment]
Nice catch!  I'll add a failing test for this, then merge your PR.

**Comment by jpdillingham** [comment]
Thanks!
