### ISSUE TITLE
Null reference error

### ISSUE THREAD

**Issue by MarkRK** [jpdillingham/Utility.CommandLine.Arguments#3]
In release 1.1.1 there is a null reference error. This was working in release 1.0.1.
The Method GetOperandsProperty fails if there are no Operands variables defined.

**Comment by jpdillingham** [comment]
Thank you for your contribution!  

I've reproduced the problem (it affects attributes too) and added two failing tests to cover these cases to the dev branch.  I'll work on an update and should have a new revision shortly.

**Comment by jpdillingham** [comment]
I was mistaken; the issue only affected operands.  PR #4 and [Release 1.1.2](https://github.com/jpdillingham/Utility.CommandLine.Arguments/releases/tag/1.1.2) resolve this issue.

Thanks again!

**Comment by MarkRK** [comment]
Nice to see it's resolved!
