### ISSUE TITLE
Arguments using only long name?

### ISSUE THREAD

**Issue by StefanH-AT** [jpdillingham/Utility.CommandLine.Arguments#62]
I'm writing a program that uses a lot of arguments and I can't map a short argument name to each of them. 

If I try to define multiple arguments like this
```c#
[Argument(' ', "mykey", "Description")]
```
the parser seems to only store the first argument. Is there something I'm missing or is this not implemented?

**Comment by jpdillingham** [comment]
Omitting a short argument name isn't supported.  This is pretty ingrained in the way the parsing logic works, so I don't see it changing.  As a workaround you might use non-printing characters.
